const express = require("express");
const router = express.Router();
const controller = require("../../controllers/client/user.controller");
const validate = require("../../validates/client/user-validate");
router.get("/register", controller.register);
router.post("/register", validate.checkRegister, controller.registerPost);
router.get("/login", controller.login);
router.post("/login", validate.checkLogin, controller.loginPost);
router.get("/logout", controller.logout);
router.get("/password/forgot",controller.forgot);
router.post("/password/forgot",controller.forgotPost);
module.exports = router;